# Use an official Node runtime as a parent image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Accept build arguments for environment variables
ARG VITE_BASE_URL=/
ARG VITE_API_URL=http://localhost:5000

# Set environment variables for build
ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_API_URL=$VITE_API_URL

# Build the app
RUN npm run build

# Install `serve` to run the application
RUN npm install -g serve

# Make port 8080 available to the world outside this container
EXPOSE 80

# Command to run the application
CMD ["serve", "-s", "dist"]
